export const WITHDRAWAL_CREATE_REQUEST = 'WITHDRAWAL_CREATE_REQUEST';
export const WITHDRAWAL_CREATE_SUCCESS = 'WITHDRAWAL_CREATE_SUCCESS';
export const WITHDRAWAL_CREATE_FAIL = 'WITHDRAWAL_CREATE_FAIL';

export const WITHDRAWAL_UPDATE_REQUEST = 'WITHDRAWAL_UPDATE_REQUEST';
export const WITHDRAWAL_UPDATE_SUCCESS = 'WITHDRAWAL_UPDATE_SUCCESS';
export const WITHDRAWAL_UPDATE_FAIL = 'WITHDRAWAL_UPDATE_FAIL';
export const WITHDRAWAL_UPDATE_RESET = 'WITHDRAWAL_UPDATE_RESET';

export const WITHDRAWAL_GETALL_REQUEST = 'WITHDRAWAL_GETALL_REQUEST';
export const WITHDRAWAL_GETALL_SUCCESS = 'WITHDRAWAL_GETALL_SUCCESS';
export const WITHDRAWAL_GETALL_FAIL = 'WITHDRAWAL_GETALL_FAIL';
export const WITHDRAWAL_GETALL_RESET = 'WITHDRAWAL_GETALL_RESET';

export const WITHDRAWAL_DETAILS_REQUEST = 'WITHDRAWAL_DETAILS_REQUEST';
export const WITHDRAWAL_DETAILS_SUCCESS = 'WITHDRAWAL_DETAILS_SUCCESS';
export const WITHDRAWAL_DETAILS_FAIL = 'WITHDRAWAL_DETAILS_FAIL';
export const WITHDRAWAL_DETAILS_RESET = 'WITHDRAWAL_DETAILS_RESET';
